ROOT_FOLDERS:
  - data/input/proj_bar
  - data/input/proj_foo

OUTPUT_FOLDER: data/output

EXCLUDE_FILES:
  - 'example.vsdx'

# specify folder relative to ROOT_FOLDER, no wildcard
EXCLUDE_FOLDERS:
  - 'data\\input\\foo\\example'

# words in the path to prepend to the output file name
QUALIFYER_NAMES:
  - AM
  - CIAM
  - Directory Services
  - IGA
  - PAM